### ISSUE TITLE
Gene Sets: output class and meta data

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-bioinformatics#9] opened 2018-03-08 13:37 UTC
##### Expected behavior
Gene Sets should output selected genes along with any metadata and class information.

##### Actual behavior
Class information and metadata is not on the output if genes are in the columns.

**Comment by JakaKokosar** [comment] 2018-04-09 11:29
Can't reproduce this. Widget sets all metadata and class variables to the output.

Can we close this?

**Comment by JakaKokosar** [comment] 2018-04-23 18:17
Closing. Reopen if the problem persists.

**Closed by JakaKokosar** 2018-04-23 18:17 UTC
